# -*- coding: utf-8 -*-
"""Customer Segmentation (Level 1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17IdlNRe3exgUo4h-dwbK-JDjD4_JKP5l
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/dataset/ifood_df.csv')
df.head()

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/dataset/ifood_df.csv')

# 1. Check missing values
missing = df.isnull().sum()

# 2. Basic stats for detecting outliers
stats = df[['Income','MntTotal']].describe()

missing, stats

import pandas as pd
from sklearn.preprocessing import StandardScaler

# Load dataset
df = pd.read_csv('/content/drive/MyDrive/dataset/ifood_df.csv')

# Select meaningful features for clustering
features = [
    'Income', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts',
    'MntFishProducts', 'MntSweetProducts', 'MntGoldProds',
    'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases',
    'NumStorePurchases', 'NumWebVisitsMonth', 'MntTotal'
]

df_selected = df[features]

# Scale the data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_selected)

scaled_data[:5]

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Load and prepare dataset again
df = pd.read_csv('/content/drive/MyDrive/dataset/ifood_df.csv')

features = [
    'Income', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts',
    'MntFishProducts', 'MntSweetProducts', 'MntGoldProds',
    'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases',
    'NumStorePurchases', 'NumWebVisitsMonth', 'MntTotal'
]

df_selected = df[features]

# Scale data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_selected)

# Run Elbow Method
wcss = []
K_RANGE = range(1, 11)

for k in K_RANGE:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_data)
    wcss.append(kmeans.inertia_)

# Plot Elbow graph
plt.figure()
plt.plot(K_RANGE, wcss, marker='o')
plt.title("Elbow Method - Optimal k")
plt.xlabel("Number of Clusters (k)")
plt.ylabel("WCSS")
plt.tight_layout()
plt.show()

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Load dataset
df = pd.read_csv('/content/drive/MyDrive/dataset/ifood_df.csv')

# Select features
features = [
    'Income', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts',
    'MntFishProducts', 'MntSweetProducts', 'MntGoldProds',
    'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases',
    'NumStorePurchases', 'NumWebVisitsMonth', 'MntTotal'
]

df_selected = df[features]

# Scale features
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_selected)

# Run K-means with k=3
kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(scaled_data)

# Add cluster column to dataset
df['Cluster'] = clusters

# Show sample
df[['Income', 'MntTotal', 'Recency', 'Cluster']].head()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Load dataset
df = pd.read_csv('/content/drive/MyDrive/dataset/ifood_df.csv')

# Select features
features = [
    'Income', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts',
    'MntFishProducts', 'MntSweetProducts', 'MntGoldProds',
    'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases',
    'NumStorePurchases', 'NumWebVisitsMonth', 'MntTotal'
]

df_selected = df[features]

# Scale features
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_selected)

# Run K-means with k=3
kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(scaled_data)

df['Cluster'] = clusters

# 1. Income vs Total Spending
plt.figure()
for cluster in df['Cluster'].unique():
    subset = df[df['Cluster'] == cluster]
    plt.scatter(subset['Income'], subset['MntTotal'])
plt.title("Income vs Total Spending (Clustered)")
plt.xlabel("Income")
plt.ylabel("Total Spending")
plt.tight_layout()
plt.show()

# 2. Recency vs Total Spending
plt.figure()
for cluster in df['Cluster'].unique():
    subset = df[df['Cluster'] == cluster]
    plt.scatter(subset['Recency'], subset['MntTotal'])
plt.title("Recency vs Total Spending (Clustered)")
plt.xlabel("Recency (days since last purchase)")
plt.ylabel("Total Spending")
plt.tight_layout()
plt.show()

# 3. 3D Cluster Plot
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

for cluster in df['Cluster'].unique():
    subset = df[df['Cluster'] == cluster]
    ax.scatter(subset['Income'], subset['Recency'], subset['MntTotal'])

ax.set_title("3D Cluster Plot: Income, Recency, Spending")
ax.set_xlabel("Income")
ax.set_ylabel("Recency")
ax.set_zlabel("Total Spending")
plt.tight_layout()
plt.show()